import { existsSync } from 'node:fs'
import { join } from 'node:path'

import pluralize from 'pluralize'

import { createDirectory, createFile } from '../../utils/index.js'

export const generateIntegrationTest = (domainName, currentPath) => {
  const testsPath = join(currentPath, 'tests')
  const filePath = join(testsPath, `${domainName}.test.js`)

  createDirectory(testsPath, true)

  if (!existsSync(filePath)) {
    const fixtureName = pluralize.singular(domainName)

    const content = [
      'import { StatusCodes } from \'http-status-codes\'',
      'import {',
      '  afterEach,',
      '  beforeEach,',
      '  describe,',
      '  jest,',
      '  expect,',
      '  test',
      '} from \'@jest/globals\'',
      'import { isPlainObject } from \'@devnetic/utils\'',
      '',
      'import { app } from \'../src/app.js\'',
      'import { dataSource } from \'../src/data-source.js\'',
      'import { drizzle } from \'./stubs/index.js\'',
      `import { createdAt, id, payload, updatedAt, ${fixtureName} } from './fixtures/index.js'`,
      'import { CONTENT_TYPE, PROBLEM_CONTENT_TYPE } from \'../src/common/index.js\'',
      '',
      `describe('${domainName}', () => {`,
      `  const endpointUrl = '/${domainName}'`,
      `  const drizzleStub = drizzle(['${domainName}'])`,
      '',
      '  beforeEach(() => {',
      '    jest.spyOn(dataSource, \'getInstance\').mockReturnValue(drizzleStub)',
      '  })',
      '',
      '  afterEach(() => {',
      '    jest.restoreAllMocks()',
      '  })',
      '',
      `  test('should create an ${fixtureName}', async () => {`,
      `    const expected = ${fixtureName}`,
      '',
      '    jest',
      '      .spyOn(drizzleStub, \'returning\')',
      `      .mockImplementation(() => Promise.resolve([${fixtureName}]))`,
      '',
      '    const response = await app.inject({',
      '      method: \'POST\',',
      '      url: endpointUrl,',
      '      payload',
      '    })',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.CREATED)',
      '    expect(response.headers[\'content-type\']).toEqual(CONTENT_TYPE)',
      '    expect(response.json()).toEqual(expected)',
      '  })',
      '',
      `  test('should throw internal server error when creating an ${fixtureName}', async () => {`,
      '    jest',
      '      .spyOn(drizzleStub, \'returning\')',
      '      .mockImplementation(() => Promise.reject(new Error()))',
      '',
      '    const response = await app.inject({',
      '      method: \'POST\',',
      '      url: endpointUrl,',
      '      payload',
      '    })',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.INTERNAL_SERVER_ERROR)',
      '    expect(response.headers[\'content-type\']).toBe(PROBLEM_CONTENT_TYPE)',
      '  })',
      '',
      `  test('should throw payload error when creating an ${fixtureName}', async () => {`,
      '    const response = await app.inject({',
      '      method: \'POST\',',
      '      url: endpointUrl',
      '    })',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.BAD_REQUEST)',
      '    expect(response.headers[\'content-type\']).toBe(PROBLEM_CONTENT_TYPE)',
      '  })',
      '',
      `  test('should patch an ${fixtureName}', async () => {`,
      '    const patchPayload = {',
      '    }',
      '',
      '    const { password, ...payloadWithoutPassword } = payload',
      '    ',
      '    const expected = {',
      '      id,',
      '      ...payloadWithoutPassword,',
      '      ...patchPayload,',
      '      created_at: createdAt,',
      '      updated_at: updatedAt',
      '    }',
      '',
      '    jest',
      '      .spyOn(drizzleStub, \'returning\')',
      '      .mockImplementation(() => Promise.resolve([expected]))',
      '    ',
      '    const response = await app.inject({',
      '      method: \'PATCH\',',
      '      url: `${endpointUrl}/${id}`,', // eslint-disable-line no-template-curly-in-string
      '      payload: patchPayload',
      '    })',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.OK)',
      '    expect(response.headers[\'content-type\']).toBe(CONTENT_TYPE)',
      '    expect(response.json()).toEqual(expected)',
      '  })',
      '',
      `  test('should delete an ${fixtureName}', async () => {`,
      '    jest',
      '      .spyOn(drizzleStub, \'where\')',
      '      .mockImplementation(() => Promise.resolve(true))',
      '',
      '    const response = await app.inject({',
      '      method: \'DELETE\',',
      '      url: `${endpointUrl}/${id}`,', // eslint-disable-line no-template-curly-in-string
      '    })',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.NO_CONTENT)',
      '    expect(response.headers[\'content-length\']).toBe(undefined)',
      '  })',
      '',
      `  test('should get all ${fixtureName}s', async () => {`,
      '    const expected = {',
      `      data: [${fixtureName}],`,
      '      total: 1',
      '    }',
      '',
      '    jest',
      `      .spyOn(drizzleStub.query.${domainName}, 'findMany')`,
      `      .mockImplementation(() => Promise.resolve([${fixtureName}]))`,
      '',
      '    jest',
      '      .spyOn(drizzleStub, \'from\')',
      '      .mockImplementation(() => Promise.resolve([{ count: expected.data.length }]))',
      '',
      '    const response = await app.inject({',
      '      method: \'GET\',',
      '      url: endpointUrl',
      '    })',
      '',
      '    const responseData = response.json()',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.OK)',
      '    expect(response.headers[\'content-type\']).toBe(CONTENT_TYPE)',
      '    expect(isPlainObject(responseData))',
      '    expect(Array.isArray(responseData.data)).toBe(true)',
      '    expect(response.json()).toEqual(expected)',
      '    expect(responseData.data.length).toBeGreaterThan(0)',
      '    expect(responseData.data[0].password).toBeUndefined()',
      '  })',
      '',
      `  test('should get an ${fixtureName} by id', async () => {`,
      `    const expected = ${fixtureName}`,
      '',
      '    jest',
      `      .spyOn(drizzleStub.query.${domainName}, 'findFirst')`,
      `      .mockImplementation(() => Promise.resolve(${fixtureName}))`,
      '',
      '    const response = await app.inject({',
      '      method: \'GET\',',
      '      url: `${endpointUrl}/${id}`,', // eslint-disable-line no-template-curly-in-string
      '    })',
      '',
      '    const responseData = response.json()',
      '',
      '    expect(response.statusCode).toBe(StatusCodes.OK)',
      '    expect(response.headers[\'content-type\']).toBe(CONTENT_TYPE)',
      '    expect(responseData).toEqual(expected)',
      '  })',
      '})',
      ''
    ]

    createFile(filePath, content.join('\n'))
  }
}
